---
- hosts: leader
  vars:
    force_purge: true
    install_public_roles: true
    installation_dir: roles/public
    installation_prefix: ../
  pre_tasks:
    - name: info
      debug: msg="Starting system setup"

    - name: set hostname
      become: yes
      hostname:
        name: "{{ lookup('env', 'NEW_HOSTNAME') | default(lookup('env', 'HOST'), True) }}"

    - name: Adding leader to swarm group
      add_host:
        name: '{{ groups.leader[0] }}'
        groups: [swarm]

    - name: update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: info
      debug: msg="Installing packages, this takes a while"

    - name: install pre-requirements
      become: yes
      apt:
        pkg:
          - acl
          - curl
          - apache2-utils
          - software-properties-common
          - ca-certificates
          - gnupg-agent
          - moreutils
          - build-essential
          - libssl-dev
          - libffi-dev
          - gcc
          - wget
          - tree
          - libpcre3
          - xfsprogs
          - btrfs-progs

    - name: install pip
      become: yes
      apt:
        pkg:
          - python3-pip
          - python3-setuptools

    - name: install pip modules
      pip:
        name:
          - netaddr
          - pyvmomi
          - docker
          - requests

    - name: Remove existing public roles
      file:
        path: '{{ installation_prefix }}{{ installation_dir }}'
        state: absent
      when: force_purge | bool

    - name: Install ansible-galaxy collection install ansible.posix
      command: >
        ansible-galaxy collection install ansible.posix

    - name: Install public roles
      command: >
        ansible-galaxy install
        {{ ( force_purge | bool ) | ternary('--force','') }}
        --role-file {{ installation_prefix }}roles/requirements.yml
        --roles-path {{ installation_prefix }}{{ installation_dir }}
      when: install_public_roles | bool
